apiVersion: v1
kind: Secret
metadata:
  name: studio
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "studio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.secrets.gitlabClientId }}
  gitlabClientId: {{ .Values.global.secrets.gitlabClientId | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.gitlabSecretKey }}
  gitlabSecretKey: {{ .Values.global.secrets.gitlabSecretKey | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.gitlabWebhookSecret }}
  gitlabWebhookSecret: {{ .Values.global.secrets.gitlabWebhookSecret | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.githubClientId }}
  githubClientId: {{ .Values.global.secrets.githubClientId | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.githubAppId }}
  githubAppId: {{ .Values.global.secrets.githubAppId | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.githubAppSecret }}
  githubAppSecret: {{ .Values.global.secrets.githubAppSecret | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.githubPrivateKey }}
  githubPrivateKey: {{ .Values.global.secrets.githubPrivateKey | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.githubWebhookSecret }}
  githubWebhookSecret: {{ .Values.global.secrets.githubWebhookSecret | b64enc }}
  {{- end }}

  # Set secretKey to existing value or generate a random one
  {{- if .Values.global.secrets.secretKey }}
  secretKey: {{ .Values.global.secrets.secretKey | b64enc }}
  {{- else }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "studio") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "secretKey") | default (randAscii 40 | b64enc) }}
  secretKey: {{ $secretKey | quote }}
  {{- end }}
  
  {{- if .Values.global.secrets.postgresDatabaseUser }}
  postgresDatabaseUser: {{ .Values.global.secrets.postgresDatabaseUser | b64enc }}
  {{- end }}
  
  {{- if .Values.global.secrets.postgresDatabasePassword }}
  postgresDatabasePassword: {{ .Values.global.secrets.postgresDatabasePassword | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.blobVaultAccessKeyId }}
  blobVaultAccessKeyId: {{ .Values.global.secrets.blobVaultAccessKeyId | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.blobVaultSecretAccessId }}
  blobVaultSecretAccessId: {{ .Values.global.secrets.blobVaultSecretAccessId | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.bitbucketSecretKey }}
  bitbucketSecretKey: {{ .Values.global.secrets.bitbucketSecretKey | b64enc }}
  {{- end }}

  {{- if .Values.global.secrets.bitbucketClientId }}
  bitbucketClientId: {{ .Values.global.secrets.bitbucketClientId | b64enc }}
  {{- end }}
