{{/*
  The purpose of this file is to create dockerconfigjson secret o pull images during the chart-testing
  tool execution in the CI. This is needed because the chart-testing tool does not support the use of
  private registries. This file is only used in the CI, and it is not used in the deployment of the
  chart.
*/}}
{{- if (hasKey .Values "ci") }}
apiVersion: v1
data:
  .dockerconfigjson: {{ include "dockerconfig" . | b64enc | quote }}
kind: Secret
metadata:
  name: iterativeai
type: kubernetes.io/dockerconfigjson
{{- end }}
