{{- if ((.Values.studioDatachainWorker).serviceAccount).create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}-events
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDatachainWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
{{- end }}
