{{- if ((.Values.studioDatachainWorker).serviceAccount).create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}-events
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDatachainWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "studio-datachain-worker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}-events
{{- end }}
