apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datachain-worker
data:
  {{- if and (or .Values.studioBackend.replicaCount .Values.studioBackend.autoscaling.enabled) (or .Values.studioDatachainWorker.replicaCount .Values.studioDatachainWorker.autoscaling.enabled) }} 
  INTERNAL_API_URL: "http://studio-backend:{{ .Values.studioBackend.service.port }}{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}/{{ include "studio.basePath" . }}{{- end }}/api"
  {{- end }}
  CELERY_LOG_LEVEL: "{{ .Values.studioDatachainWorker.logLevel | default "info" | lower }}"
  LOG_JSON_FORMATTER: "True"
  DATACHAIN_K8S_JOB_AUTOSCALER: "True"
  {{ if ((.Values.studioPypiCache).enabled) }}
  DATACHAIN_PYPI_PROXY_URL: "http://{{ .Release.Name }}-pypi-cache:{{ .Values.studioPypiCache.service.port }}/simple/"
  {{ end }}
  XDG_CACHE_HOME: "/tmp/local/cache"
  TMPDIR: "/tmp/local"
{{- with .Values.studioDatachainWorker.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}
