apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-worker
data:
{{- with .Values.studioWorker.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}
{{- include "studio.dvcx.configMap" . | indent 2}}
