apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datachain-worker
data:
  INTERNAL_API_URL: "http://studio-backend:{{ .Values.studioBackend.service.port }}{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}/{{ include "studio.basePath" . }}{{- end }}/api"
  CELERY_LOG_LEVEL: "{{ .Values.studioDatachainWorker.logLevel | default "info" | lower }}"
  LOG_JSON_FORMATTER: "True"
  DATACHAIN_K8S_JOB_AUTOSCALER: "True"
{{- with .Values.studioDatachainWorker.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}
