{{$webhookHost := .Values.global.scmProviders.webhookHost | default .Values.global.host }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: studio
data:
{{- with .Values.global.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}

  ALLOWED_HOSTS: "*"
  API_URL: "{{ include "scheme" . }}://{{.Values.global.host }}{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}/{{ include "studio.basePath" . }}{{- end }}/api"
  UI_URL: "{{ include "scheme" . }}://{{.Values.global.host }}/{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}{{ include "studio.basePath" . }}{{- end }}"

  {{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}
  BASE_PATH: /{{ include "studio.basePath" . }}
  {{- end }}

  {{- if .Values.global.scmProviders.bitbucket.enabled }}
  BITBUCKET_ENABLED: {{ .Values.global.scmProviders.bitbucket.enabled | default false | quote | title }}
  {{- end }}
  {{- if .Values.global.scmProviders.bitbucket.url }}
  BITBUCKET_URL: {{.Values.global.scmProviders.bitbucket.url | quote }}
  {{- end }}
  {{- if .Values.global.scmProviders.bitbucket.apiUrl }}
  BITBUCKET_API_URL: {{ .Values.global.scmProviders.bitbucket.apiUrl | quote}}
  {{- end }}
  {{- if and .Values.global.scmProviders.bitbucket.enabled $webhookHost }}
  BITBUCKET_WEBHOOK_URL: "{{ include "scheme" . }}://{{ $webhookHost }}/webhook/bitbucket/"
  {{- end }}

  ENABLE_BLOBVAULT: "True"

  {{- if .Values.global.blobvault.bucket }}
  BLOBVAULT_BUCKET: {{ .Values.global.blobvault.bucket | quote }}
  {{- if .Values.global.blobvault.regionName }}
  BLOBVAULT_AWS_REGION: {{ .Values.global.blobvault.regionName }}
  {{- end }}
  {{- if .Values.global.blobvault.endpointUrl }}
  BLOBVAULT_ENDPOINT_URL: {{ .Values.global.blobvault.endpointUrl }}
  BLOBVAULT_ENDPOINT_URL_FE: {{ .Values.global.blobvault.endpointUrl }}
  {{- end }}
  {{- else }}
  BLOBVAULT_LOCAL_ENABLED: "True"
  BLOBVAULT_LOCAL_PATH: "/blobvault"
  BLOBVAULT_ENDPOINT_URL: "{{ include "scheme" . }}://{{.Values.global.host }}{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}/{{ include "studio.basePath" . }}{{- end }}/blobvault"
  BLOBVAULT_ENDPOINT_URL_FE: "{{ include "scheme" . }}://{{.Values.global.host }}{{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}/{{ include "studio.basePath" . }}{{- end }}/blobvault"
  {{- end }}

  {{- if .Values.global.celery.brokerUrl }}
  CELERY_BROKER_URL: {{ .Values.global.celery.brokerUrl }}
  {{- else }}
  CELERY_BROKER_URL: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}

  {{- if .Values.global.celery.resultBackend }}
  CELERY_RESULT_BACKEND: {{ .Values.global.celery.resultBackend }}
  {{- else }}
  CELERY_RESULT_BACKEND: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}

  {{- if .Values.global.celery.resultBackend }}
  REDIS_URL: {{ .Values.global.celery.resultBackend }}
  {{- else }}
  REDIS_URL: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}

  {{- if .Values.global.scmProviders.github.enabled }}
  GITHUB_ENABLED: {{ .Values.global.scmProviders.github.enabled | default false | quote | title }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.apiUrl }}
  GITHUB_API_URL: {{ .Values.global.scmProviders.github.apiUrl | quote }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.url }}
  GITHUB_URL: {{ .Values.global.scmProviders.github.url | quote }}
  {{- end }}
  {{- if and .Values.global.scmProviders.github.enabled $webhookHost }}
  GITHUB_WEBHOOK_URL: "{{ include "scheme" . }}://{{ $webhookHost }}/webhook/github/"
  {{- end }}
  {{- if .Values.global.scmProviders.github.clientId }}
  GITHUB_APP_CLIENT_ID: {{ .Values.global.scmProviders.github.clientId | quote }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.appId }}
  GITHUB_APP_ID: {{ .Values.global.scmProviders.github.appId | quote }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.appName }}
  GITHUB_APP_NAME: {{ .Values.global.scmProviders.github.appName | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.gitlab.enabled }}
  GITLAB_ENABLED: {{ .Values.global.scmProviders.gitlab.enabled | default false | quote | title }}
  {{- end }}
  {{- if .Values.global.scmProviders.gitlab.url }}
  GITLAB_URL: {{ .Values.global.scmProviders.gitlab.url | quote}}
  {{- end }}
  {{- if and .Values.global.scmProviders.gitlab.enabled $webhookHost }}
  GITLAB_WEBHOOK_URL: "{{ include "scheme" . }}://{{ $webhookHost }}/webhook/gitlab/"
  {{- end }}

  {{- if .Values.global.maxViews }}
  MAX_VIEWS: {{ .Values.global.maxViews | quote }}
  {{- end }}
  {{- if .Values.global.maxTeams }}
  MAX_TEAMS: {{ .Values.global.maxTeams | quote }}
  {{- end }}

  {{- $scmProviders := list }}
  {{- if .Values.global.scmProviders.gitlab.enabled }}
  {{- $scmProviders = append $scmProviders "gitlab" }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.enabled }}
  {{- $scmProviders = append $scmProviders "github" }}
  {{- end }}
  {{- if .Values.global.scmProviders.bitbucket.enabled }}
  {{- $scmProviders = append $scmProviders "bitbucket" }}
  {{- end }}
  SCM_PROVIDERS: {{ $scmProviders | join "," | quote }}

  SOCIAL_AUTH_REDIRECT_IS_HTTPS: "False"

  {{- if .Values.global.host }}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: "studio-ui.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioUi.service.port }},studio-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioBackend.service.port }},{{ .Values.global.host }}"
  {{- else }}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: "studio-ui.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioUi.service.port }},studio-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioBackend.service.port }}"
  {{- end }}

  {{- $dvcx := .Values.global.dvcx | default dict }}
  {{- $dvcxClickhouse := $dvcx.clickHouse | default dict }}
  DVCX_ENABLED: {{ $dvcx.enabled | default false | quote | title }}
  DVCX_UDF_ENABLED: {{ $dvcx.udfEnabled | default false | quote | title }}
