apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datachain-worker
data:
  CELERY_LOG_LEVEL: "{{ .Values.studioDatachainWorker.logLevel | default "info" | lower }}"
  LOG_JSON_FORMATTER: "True"
  DATACHAIN_K8S_JOB_AUTOSCALER: "True"
  {{ if ((.Values.studioPypiCache).enabled) }}
  DATACHAIN_PYPI_PROXY_URL: "http://{{ .Release.Name }}-pypi-cache:{{ .Values.studioPypiCache.service.port }}"
  {{ end }}
{{- with .Values.studioDatachainWorker.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}
