apiVersion: v1
kind: ConfigMap
metadata:
  name: studio
data:
  ALLOWED_HOSTS: "*"
  API_URL:  "http{{ if $.Values.studioBackend.ingress.tlsEnabled }}s{{ end }}://{{ .Values.studioBackend.ingress.host }}/"
  UI_URL: "http{{ if $.Values.studioUi.ingress.tlsEnabled }}s{{ end }}://{{ .Values.studioUi.ingress.host }}/"

  ENABLE_SSL_FOR_WEBHOOK: {{ .Values.global.scmProviders.enableWebhookSSL | default "false" | quote | title }}

  BITBUCKET_URL: {{.Values.global.scmProviders.bitbucket.url  | default "https://bitbucket.org" | quote }}
  BITBUCKET_API_URL: {{ .Values.global.scmProviders.bitbucket.apiUrl | default "https://api.bitbucket.org" | quote}}
  BITBUCKET_WEBHOOK_URL: {{ .Values.global.scmProviders.bitbucket.webhookUrl | default "" | quote}}

  ENABLE_BLOBVAULT: "True"
  {{- if .Values.global.blobvault.endpointUrl }}
  BLOBVAULT_ENDPOINT_URL: {{ .Values.global.blobvault.endpointUrl }}
  {{- else }}
  BLOBVAULT_ENDPOINT_URL: "{{ .Values.minio.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
  {{- end }}

  {{- if .Values.global.blobvault.endpointUrlFe }}
  BLOBVAULT_ENDPOINT_URL_FE: {{ .Values.global.blobvault.endpointUrlFe }}
  {{- else }}
  BLOBVAULT_ENDPOINT_URL_FE: "{{ .Values.minio.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
  {{- end }}
  BLOBVAULT_BUCKET: {{.Values.global.blobvault.bucket | default "" | quote }}
  {{- if .Values.global.celery.brokerUrl }}
  CELERY_BROKER_URL: {{ .Values.global.celery.brokerUrl }}
  {{- else }}
  CELERY_BROKER_URL: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}
  {{- if .Values.global.celery.resultBackend }}
  CELERY_RESULT_BACKEND: {{ .Values.global.celery.resultBackend }}
  {{- else }}
  CELERY_RESULT_BACKEND: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}
  {{- if .Values.global.celery.resultBackend }}
  REDIS_URL: {{ .Values.global.celery.resultBackend }}
  {{- else }}
  REDIS_URL: "redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  {{- end }}
  GITHUB_API_URL: {{ .Values.global.scmProviders.github.apiUrl | default "https://api.github.com" | quote }}
  GITHUB_URL: {{ .Values.global.scmProviders.github.url | default "https://github.com" | quote }}
  GITHUB_WEBHOOK_URL: {{ .Values.global.scmProviders.github.webhookUrl | default "" | quote }}
  GITLAB_URL: {{ .Values.global.scmProviders.gitlab.url | default "" | quote}}
  GITLAB_WEBHOOK_URL: {{ .Values.global.scmProviders.gitlab.webhookUrl | default "https://gitlab.com" | quote }}
  MAX_VIEWS: {{ .Values.global.maxViews | default "" | quote }}
  MAX_TEAMS: {{ .Values.global.maxTeams | default "" | quote }}
  {{- $scmProviders := list }}
  {{- if .Values.global.scmProviders.gitlab.enabled }}
  {{- $scmProviders = append $scmProviders "gitlab" }}
  {{- end }}
  {{- if .Values.global.scmProviders.github.enabled }}
  {{- $scmProviders = append $scmProviders "github" }}
  {{- end }}
  {{- if .Values.global.scmProviders.bitbucket.enabled }}
  {{- $scmProviders = append $scmProviders "bitbucket" }}
  {{- end }}
  SCM_PROVIDERS: {{ $scmProviders | join "," | quote}}
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: "False"
  {{- if .Values.studioUi.ingress.enabled }}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: "studio-ui.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioUi.service.port }},studio-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioBackend.service.port }},http{{ if $.Values.studioUi.ingress.tlsEnabled }}s{{ end }}://{{ .Values.studioUi.ingress.host }}/"
  {{- else }}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: "studio-ui.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioUi.service.port }},studio-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.studioBackend.service.port }}"
  {{- end }}
