apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-backend
data:
{{- with .Values.studioBackend.envVars}}
{{-  toYaml . | nindent 2 }}
{{- end }}

  LEO_SERVICE_HOST: "{{ .Release.Name }}-studio-leo"
  LEO_SERVICE_PORT: "{{ .Values.studioLeo.service.port }}"
  LEO_ENCODING: "utf-8"

