apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-beat
  labels:
    {{- include "studio-beat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studioBeat.autoscaling.enabled }}
  replicas: {{ .Values.studioBeat.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio-beat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-studio-beat: {{ include (print $.Template.BasePath "/configmap-studio-beat.yaml") . | sha256sum }}
        {{- include "studio.checksum" . | indent 8 }}
        {{- with .Values.studioBeat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "studio-beat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studioBeat.podSecurityContext | nindent 8 }}
      containers:
        - name: studio-beat
          securityContext:
            {{- toYaml .Values.studioBeat.securityContext | nindent 12 }}
          image: "{{ .Values.studioBackend.image.repository }}:{{ .Values.studioBackend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studioBackend.image.pullPolicy }}
          args: ["/app/bin/run_celery_beat.sh"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.studioBeat.resources | nindent 12 }}
          env:
            - name: "NO_MIGRATE_DB"
              value: "1"
            - name: "WAIT_FOR_MIGRATIONS"
              value: "1"
          envFrom:
            - configMapRef:
                name: studio
            - configMapRef:
                name: studio-beat
            - secretRef:
                name: studio
            {{- if .Values.global.envFromSecret }}
            - secretRef:
                name: {{ .Values.global.envFromSecret }}
            {{- end }}
            {{- if .Values.studioBeat.envFromSecret }}
            - secretRef:
                name: {{ .Values.studioBeat.envFromSecret }}
            {{- end }}
          volumeMounts:
            - name: studio-ca-certificates
              mountPath: /usr/local/share/ca-certificates
      volumes:
        - name: studio-ca-certificates
          configMap:
            name: studio-ca-certificates
      {{- with .Values.studioBeat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioBeat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioBeat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
