apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-backend
  labels:
    {{- include "studio-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studioBackend.autoscaling.enabled }}
  replicas: {{ .Values.studioBackend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.studioBackend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studioBackend.podSecurityContext | nindent 8 }}
      containers:
        - name: studio-backend
          securityContext:
            {{- toYaml .Values.studioBackend.securityContext | nindent 12 }}
          image: "{{ .Values.studioBackend.image.repository }}:{{ .Values.studioBackend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studioBackend.image.pullPolicy }}
          args: ["uwsgi", "--ini", "uwsgi.ini"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health?format=json
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 25
            timeoutSeconds: 60
          resources:
            {{- toYaml .Values.studioBackend.resources | nindent 12 }}
          env:
            {{ include "studio.envvars" . | indent 12 }}
      {{- with .Values.studioBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioBackend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioBackend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
