apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-ui
  labels:
    {{- include "studio-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studioUi.autoscaling.enabled }}
  replicas: {{ .Values.studioUi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "studio.checksum" . | indent 8 }}
      {{- with .Values.studioUi.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studioUi.podSecurityContext | nindent 8 }}
      containers:
        - name: studio-ui
          securityContext:
            {{- toYaml .Values.studioUi.securityContext | nindent 12 }}
          image: "{{ .Values.studioUi.image.repository }}:{{ .Values.studioUi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studioUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
            {{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}
              path: /{{ include "studio.basePath" . }}/api/health
            {{- else }}
              path: /api/health
            {{- end }}
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 25
            timeoutSeconds: 10
          envFrom:
            - configMapRef:
                name: studio
            - configMapRef:
                name: studio-ui
            - secretRef:
                name: studio
          {{- if .Values.global.customCaCert }}
          volumeMounts:
            - name: studio-ca-certificates
              mountPath: /usr/local/share/ca-certificates
          {{- end }}
          resources:
            {{- toYaml .Values.studioUi.resources | nindent 12 }}
      {{- if .Values.global.customCaCert }}
      volumes:
        - name: studio-ca-certificates
          configMap:
            name: studio-ca-certificates
      {{- end }}
      {{- with .Values.studioUi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioUi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioUi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
