apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-dvcx-worker
  labels:
    {{- include "studio-dvcx-worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studioDvcxWorker.autoscaling.enabled }}
  {{- if ((.Values.global.dvcx).udfEnabled) }}
  replicas: {{ .Values.studioDvcxWorker.replicaCount }}
  {{- else }}
  replicas: 0
  {{- end }}
  {{- end }}
  {{- with .Values.studioDvcxWorker.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio-dvcx-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-studio-dvcx-worker: {{ include (print $.Template.BasePath "/configmap-studio-dvcx-worker.yaml") . | sha256sum }}
        {{- include "studio.checksum" . | indent 8 }}
        {{- with .Values.studioDvcxWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "studio-dvcx-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio-dvcx-worker.serviceAccountName" . }}
      terminationGracePeriodSeconds: 150
      securityContext:
        fsGroup: 103
        fsGroupChangePolicy: "OnRootMismatch"
        {{- with .Values.studioDvcxWorker.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: studio-dvcx-worker
          securityContext:
            {{- toYaml .Values.studioDvcxWorker.securityContext | nindent 12 }}
          image: "{{ .Values.studioDvcxWorker.image.repository }}:{{ .Values.studioDvcxWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studioDvcxWorker.image.pullPolicy }}
          args: ["/app/bin/run_celery_worker_udf.sh"]
          resources:
            {{- toYaml .Values.studioDvcxWorker.resources | nindent 12 }}
          env:
            - name: "NO_MIGRATE_DB"
              value: "1"
            - name: "WAIT_FOR_MIGRATIONS"
              value: "1"
          envFrom:
            - configMapRef:
                name: studio
            - configMapRef:
                name: {{ .Release.Name }}-dvcx-worker
            - secretRef:
                name: studio
            {{- if .Values.global.envFromSecret }}
            - secretRef:
                name: {{ .Values.global.envFromSecret }}
            {{- end }}
            {{- if .Values.studioDvcxWorker.envFromSecret }}
            - secretRef:
                name: {{ .Values.studioDvcxWorker.envFromSecret }}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - 'from viewer.utils import sqlalchemy_liveness_probe; sqlalchemy_liveness_probe()'
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            {{- if not .Values.global.blobvault.bucket }}
            - name: blobvault
              mountPath: /blobvault
            {{- end }}
            - name: studio-ca-certificates
              mountPath: /usr/local/share/ca-certificates
            - name: tmp-ephemeral
              mountPath: /tmp/shared
            - name: tmp-local
              mountPath: /tmp/local
      volumes:
        {{- if not .Values.global.blobvault.bucket }}
        - name: blobvault
          persistentVolumeClaim:
            claimName: blobvault
        {{- end }}
        - name: studio-ca-certificates
          configMap:
            name: studio-ca-certificates
        - name: tmp-ephemeral
          {{- if eq .Values.studioDvcxWorker.ephemeralStorage.type "ephemeral" }}
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: {{.Release.Name}}-{{ .Values.studioDvcxWorker.ephemeralStorage.persistentVolumeClaim.claimName }}
              spec:
                accessModes: [ "ReadWriteOnce" ]
                {{- if .Values.studioDvcxWorker.ephemeralStorage.persistentVolumeClaim.storageClass }}
                storageClassName: {{ .Values.studioDvcxWorker.ephemeralStorage.persistentVolumeClaim.storageClass }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ .Values.studioDvcxWorker.ephemeralStorage.size }}
          {{- else if eq .Values.studioDvcxWorker.ephemeralStorage.type "pvc" }}
          persistentVolumeClaim:
              claimName: {{ .Values.studioDvcxWorker.ephemeralStorage.persistentVolumeClaim.claimName }}
          {{- else if eq .Values.studioDvcxWorker.ephemeralStorage.type "pvcRWX" }}
          persistentVolumeClaim:
              claimName: {{.Release.Name}}-studio-dvcx-worker-ephemeral-rwx
          {{- else if eq .Values.studioDvcxWorker.ephemeralStorage.type "emptyDir"}}
          emptyDir:
            sizeLimit: {{ .Values.studioDvcxWorker.ephemeralStorage.size }}
          {{- end }}
        {{- with .Values.studioDvcxWorker.localStorage }}
        - name: tmp-local
          {{- if eq .type "ephemeral" }}
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: {{ $.Release.Name }}-{{ .persistentVolumeClaim.claimName }}
              spec:
                accessModes: [ "ReadWriteOnce" ]
                {{- if .persistentVolumeClaim.storageClass }}
                storageClassName: {{ .persistentVolumeClaim.storageClass }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ .size }}
          {{- else if eq .type "pvc" }}
          persistentVolumeClaim:
              claimName: {{ .persistentVolumeClaim.claimName }}
          {{- else if eq .type "emptyDir"}}
          emptyDir:
            sizeLimit: {{ .size }}
          {{- end }}
        {{- end }}
      {{- with .Values.studioDvcxWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioDvcxWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studioDvcxWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
