{{- if ((.Values.studioBackend.datachainApi).autoscaling.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: studio-datachain-api
  labels:
    {{- include "studio-datachain-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studio-datachain-api
  minReplicas: {{ ((.Values.studioBackend.datachainApi).autoscaling.minReplicas) }}
  maxReplicas: {{ ((.Values.studioBackend.datachainApi).autoscaling.maxReplicas) }}
  metrics:
    {{- if ((.Values.studioBackend.datachainApi).autoscaling.targetMemoryUtilizationPercentage) }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ ((.Values.studioBackend.datachainApi).autoscaling.targetMemoryUtilizationPercentage) }}
    {{- end }}
    {{- if ((.Values.studioBackend.datachainApi).autoscaling.targetCPUUtilizationPercentage) }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ ((.Values.studioBackend.datachainApi).autoscaling.targetCPUUtilizationPercentage) }}
    {{- end }}
{{- end }}
