{{- if .Values.studioDvcxWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Release.Name}}-dvcx-worker
  labels:
    {{- include "studio-dvcx-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDvcxWorker.autoscaling.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studio-dvcx-worker
  {{- if ((.Values.global.dvcx).udfEnabled) }}
  minReplicas: {{ .Values.studioDvcxWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.studioDvcxWorker.autoscaling.maxReplicas }}
  {{- else }}
  minReplicas: 0
  maxReplicas: 0
  {{- end}}
  metrics:
    {{- if .Values.studioDvcxWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.studioDvcxWorker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.studioDvcxWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.studioDvcxWorker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- with .Values.studioDvcxWorker.autoscaling.template }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.studioDvcxWorker.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
