{{- if .Values.global.ingress.enabled -}}
{{- if and .Values.global.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.global.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.global.ingress.annotations "kubernetes.io/ingress.class" .Values.global.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-studio-api
  labels:
    {{- include "studio-backend.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.global.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- with .Values.global.ingress }}
  {{- if and .tlsEnabled .hostnameEnabled .tlsSecretName }}
  tls:
    - hosts:
        - {{ $.Values.global.host }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- if ((.Values.studioBackend.datachainApi).enabled) }}
          {{- $paths := list "management" "metastore" "jobs" }}
          {{- range $p := $paths }}
          {{- if and $.Values.global.basePath (not (eq $.Values.global.basePath "/")) }}
          - path: /{{ include "studio.basePath" . }}/api/{{ $p }}
          {{- else }}
          - path: /api/{{ $p }}
          {{- end }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: studio-datachain-api
                port:
                  number: {{ $.Values.studioBackend.service.port }}
              {{- else }}
              serviceName: studio-datachain-api
              servicePort: {{ $.Values.studioBackend.service.port }}
              {{- end }}
          {{- end }}
          {{- end }}

          {{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}
          - path: /{{ include "studio.basePath" . }}/api
          {{- else }}
          - path: /api
          {{- end }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: studio-backend
                port:
                  number: {{ .Values.studioBackend.service.port }}
              {{- else }}
              serviceName: studio-backend
              servicePort: {{ .Values.studioBackend.service.port }}
              {{- end }}
      {{- if .Values.global.ingress.hostnameEnabled }}
      host: {{ .Values.global.host }}
      {{- end }}
{{- end }}
