{{- if .Values.global.ingress.enabled -}}
{{- if and .Values.global.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.global.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.global.ingress.annotations "kubernetes.io/ingress.class" .Values.global.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-studio-ui
  labels:
    {{- include "studio-ui.labels" . | nindent 4 }}
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: "delete"
    argocd.argoproj.io/hook: PostSync
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.global.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- with .Values.global.ingress }}
  {{- if and .tlsEnabled .hostnameEnabled .tlsSecretName }}
  tls:
    - hosts:
        - {{ $.Values.global.host }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}
          - path: /{{ include "studio.basePath" . }}
          {{- else }}
          - path: /
          {{- end }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: studio-ui
                port:
                  number: {{ .Values.studioUi.service.port }}
              {{- else }}
              serviceName: studio-ui
              servicePort: {{ .Values.studioUi.service.port }}
              {{- end }}
      {{- if .Values.global.ingress.hostnameEnabled }}
      host: {{ .Values.global.host }}
      {{- end }}
{{- end }}
