---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobvault
spec:
  accessModes:
  {{- with .Values.global.blobvault.persistentVolume.accessModes }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  storageClassName: {{ .Values.global.blobvault.persistentVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.global.blobvault.persistentVolume.size }}
