---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobvault
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.blobvault.persistentVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.global.blobvault.persistentVolume.size }}
