---
{{ if not .Values.global.blobvault.bucket }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blobvault
spec:
  accessModes:
  {{- with .Values.global.blobvault.persistentVolume.accessModes }}
  {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- $pvc := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "blobvault") | default dict }}
  {{- $pvcSpec := (get $pvc "spec") | default dict }}
  {{- $storageClassName := (get $pvcSpec "storageClassName") | default $.Values.global.blobvault.persistentVolume.storageClassName }}
  {{- if $storageClassName }}
  storageClassName: {{ $storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.global.blobvault.persistentVolume.size }}
{{- end }}
