{{- if eq .Values.studioDatachainWorkerJobTemplate.ephemeralStorage.type "pvcRWX" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name}}-studio-datachain-worker-ephemeral-rwx
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.studioDatachainWorkerJobTemplate.ephemeralStorage.persistentVolumeClaim.storageClass }}
  resources:
    requests:
      storage:  {{ .Values.studioDatachainWorkerJobTemplate.ephemeralStorage.size }}
{{- end }}
