{{- if ((.Values.studioDatachainWorker).serviceAccount).create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDatachainWorker.serviceAccount.annotations }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "resourcequotas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
{{- end }}
