apiVersion: v1
kind: Secret
metadata:
  name: studio-migration-job
data:
  DATABASE_URL: "psql://{{ .Values.global.postgres.databaseUser}}:{{ .Values.global.postgres.databasePassword }}@{{ .Values.global.postgres.databaseUrl }}"
