apiVersion: v1
kind: Secret
metadata:
  name: studio
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "psql://{{ .Values.global.postgres.databaseUser}}:{{ .Values.global.postgres.databasePassword }}@{{ .Values.global.postgres.databaseUrl }}"

  {{- if .Values.global.scmProviders.gitlab.clientId }}
  GITLAB_CLIENT_ID: {{ .Values.global.scmProviders.gitlab.clientId | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.gitlab.secretKey }}
  GITLAB_SECRET_KEY: {{ .Values.global.scmProviders.gitlab.secretKey | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.gitlab.webhookSecret }}
  GITLAB_WEBHOOK_SECRET: {{ .Values.global.scmProviders.gitlab.webhookSecret | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.github.appSecret }}
  GITHUB_APP_SECRET_KEY: {{ .Values.global.scmProviders.github.appSecret | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.github.privateKey }}
  GITHUB_APP_PRIVATE_KEY_PEM: |- {{ .Values.global.scmProviders.github.privateKey | nindent 4 }}
  {{- end }}

  {{- if .Values.global.scmProviders.github.webhookSecret }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.global.scmProviders.github.webhookSecret | quote }}
  {{- end }}

  # Set secretKey to existing value or generate a random one
  {{- if .Values.global.secretKey }}
  SECRET_KEY: {{ .Values.global.secretKey | quote }}
  {{- else }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "studio") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := ((get $secretData "SECRET_KEY") | b64dec) | default (randAscii 40) }}
  SECRET_KEY: {{ $secretKey | quote }}
  {{- end }}

  {{- if .Values.global.blobvault.accessKeyId }}
  BLOBVAULT_AWS_ACCESS_KEY_ID: {{ .Values.global.blobvault.accessKeyId | quote }}
  {{- end }}

  {{- if .Values.global.blobvault.secretAccessKeyId }}
  BLOBVAULT_AWS_SECRET_ACCESS_ID: {{ .Values.global.blobvault.secretAccessKeyId | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.bitbucket.secretKey }}
  BITBUCKET_SECRET_KEY: {{ .Values.global.scmProviders.bitbucket.secretKey | quote }}
  {{- end }}

  {{- if .Values.global.scmProviders.bitbucket.clientId }}
  BITBUCKET_CLIENT_ID: {{ .Values.global.scmProviders.bitbucket.clientId | quote }}
  {{- end }}
