{{- if (hasKey .Values "ci") }}
apiVersion: v1
data:
  .dockerconfigjson: {{ include "dockerconfig" . | b64enc | quote }}
kind: Secret
metadata:
  name: iterativeai
type: kubernetes.io/dockerconfigjson
{{- end }}
