{{- if ((.Values.pgBouncer).enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer
  {{ if (not (hasKey .Values "ci")) }} # Add annotation if we're not in CI execution.
  annotations:
    helm.sh/resource-policy: "keep"
    argocd.argoproj.io/sync-options: Delete=false
  {{- end }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_USERNAME: {{ .Values.global.postgres.user | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.global.postgres.password | quote }}
  POSTGRESQL_DATABASE: {{ .Values.global.postgres.databaseName | quote }}
  POSTGRESQL_HOST: {{ .Values.global.postgres.host | quote }}
  POSTGRESQL_PORT: {{ .Values.global.postgres.port | quote }}
  PGBOUNCER_DATABASE: {{ .Values.global.postgres.databaseName | quote }}
{{- end }}