apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blobvault-nginx
  labels:
    {{- include "studio-blobvault-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studioBackend.service.type }}
  ports:
    - port: {{ .Values.studioBlobvault.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "studio-blobvault-nginx.selectorLabels" . | nindent 4 }}
