apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-datachain-worker
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studioDatachainWorker.service.type }}
  ports:
    - port: {{ .Values.studioDatachainWorker.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "studio-datachain-worker.selectorLabels" . | nindent 4 }}
