{{- if ((.Values.studioBackend.datachainApi).enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: studio-datachain-api
  labels:
    {{- include "studio-datachain-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studioBackend.service.type }}
  ports:
    - port: {{ .Values.studioBackend.service.port }}
      {{- if and .Values.global.basePath (not (eq .Values.global.basePath "/")) }}
      targetPort: nginx-http
      {{- else }}
      targetPort: studio-http
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "studio-datachain-api.selectorLabels" . | nindent 4 }}
{{- end }}
