{{- if ((.Values.studioWorker).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-worker.serviceAccountName" . }}
  labels:
    {{- include "studio-worker.labels" . | nindent 4 }}
  {{- with .Values.studioWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
