apiVersion: v1
kind: Service
metadata:
  name: studio-ui
  labels:
    {{- include "studio-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studioUi.service.type }}
  ports:
    - port: {{ .Values.studioUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: nginx-http
      protocol: TCP
      name: nginx-http
  selector:
    {{- include "studio-ui.selectorLabels" . | nindent 4 }}
