{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio.serviceAccountName" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
