{{- if ((.Values.studioDvcxWorker).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-dvcx-worker.serviceAccountName" . }}
  labels:
    {{- include "studio-dvcx-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDvcxWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
