{{- if ((.Values.studioBackend).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-backend.serviceAccountName" . }}
  labels:
    {{- include "studio-backend.labels" . | nindent 4 }}
  {{- with .Values.studioBackend.serviceAccount.annotations }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
