{{- if ((.Values.studioDatachainWorker).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDatachainWorker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
