apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector/ingress-ready
    target:
      kind: Deployment
