name: Helm

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  changes:
    name: Check for updated charts
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'iterative/helm-charts')
    outputs:
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/studio/Chart.yaml'
              - 'charts/studio/values.yaml'

  release:
    name: Release chart
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    needs:
      - changes
    if: |
      (github.repository == 'iterative/helm-charts') &&
      (needs.changes.outputs.charts == 'true')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add repositories for dependencies
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          config: .github/chart-releaser-config.yaml
          CR_SKIP_EXISTING: "false"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
