name: Leaked Secrets Scan
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - if: github.ref_name != 'main'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      - if: github.ref_name == 'main'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified
